
package tatoo.soap;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * WSDL for the tatoo webservice
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TatooWebservice", targetNamespace = "http://wafriv.de/tatoo_webservice/wsdl.php", wsdlLocation = "http://wafriv.de/tatoo_webservice/wsdl.php")
public class TatooWebservice
    extends Service
{

    private final static URL TATOOWEBSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(tatoo.soap.TatooWebservice.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = tatoo.soap.TatooWebservice.class.getResource(".");
            url = new URL(baseUrl, "http://wafriv.de/tatoo_webservice/wsdl.php");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://wafriv.de/tatoo_webservice/wsdl.php', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TATOOWEBSERVICE_WSDL_LOCATION = url;
    }

    public TatooWebservice(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TatooWebservice() {
        super(TATOOWEBSERVICE_WSDL_LOCATION, new QName("http://wafriv.de/tatoo_webservice/wsdl.php", "TatooWebservice"));
    }

    /**
     * 
     * @return
     *     returns TatooWebservicePortType
     */
    @WebEndpoint(name = "TatooWebservicePort")
    public TatooWebservicePortType getTatooWebservicePort() {
        return super.getPort(new QName("http://wafriv.de/tatoo_webservice/wsdl.php", "TatooWebservicePort"), TatooWebservicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TatooWebservicePortType
     */
    @WebEndpoint(name = "TatooWebservicePort")
    public TatooWebservicePortType getTatooWebservicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wafriv.de/tatoo_webservice/wsdl.php", "TatooWebservicePort"), TatooWebservicePortType.class, features);
    }

}
